### ISSUE TITLE
Can't set attribute for learning rate

### ISSUE THREAD

**Issue by pzhenwen** [CyberZHG/keras-gradient-accumulation#2]
Hello,

Installed your package and it turned out having issues of setting learning rate. Would you mind taking a look. Thank you!

```python

~\Anaconda3\lib\site-packages\keras_gradient_accumulation\optimizers.py in get_updates(self, loss, params)
     76 
     77         # Use fake learning rate
---> 78         self.optimizer.lr = K.switch(update_cond, self.lr, 0.0)
     79 
     80         # Freeze momentum

AttributeError: can't set attribute

```

**Comment by dimitreOliveira** [comment]
To add further information, 

I'm also having this issue, for me, this happens in the Kaggle environment, but on Google colab everything works fine, so I suppose it's something related to the VM environment.

**Comment by pzhenwen** [comment]
> To add further information,
> 
> I'm also having this issue, for me, this happens in the Kaggle environment, but on Google colab everything works fine, so I suppose it's something related to the VM environment.

Thanks Dimitre.

I think you are right. It seems to be the issue of the keras.optimizers installed in my local machine. I was trying another custom optimizer needing to initialize the learning rate (lr) inherited from keras/optimizers.py and it turned out having the same error. But when I put the exact same code on colab and it ran fine. To me, it could be due to the keras backend or something wrong with the codes in the keras/optimizer. 

Any idea how to fix it?

**Comment by CyberZHG** [comment]
keras 2.2.4 => lr
keras 2.3.0 => learning_rate

**Comment by dimitreOliveira** [comment]
I have tested the updated version and it works fine, thanks @CyberZHG

**Comment by pzhenwen** [comment]
Thank you both. @CyberZHG @dimitreOliveira.

After I was using the later version and changed the name to learning rate, the code finally worked. Thank you!

**Comment by aaronlockhartdev** [comment]
I'm still having this issue on keras 2.3.1. I get AttributeError: can't set attribute. Changing AdaBound lr to learning_rate doesn't work.

**Comment by RichardChangCA** [comment]
> I'm still having this issue on keras 2.3.1. I get AttributeError: can't set attribute. Changing AdaBound lr to learning_rate doesn't work.

I think this is because the keras backend tensorflow version is not the proper one. Just try TensorFlow 2.0 instead of below and 2.1

**Comment by vikassalaria2412** [comment]
> k

This solution is working.In jupyter notebook please check keras version and then use lr or learning_rate

**Comment by vikassalaria2412** [comment]
> keras 2.2.4 => lr
> keras 2.3.0 => learning_rate
This solution is working.In jupyter notebook please check keras version and then use lr or learning_rate

**Comment by Kosisochi** [comment]
I'm getting this error on Keras 2.4.3. I have tried both lr and learning_rate with no success. 

is Keras Adam compatible with 2.4.3
