### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by dlamm1997** [CyberZHG/keras-gradient-accumulation#7]
I keep getting this __init__() error when trying to construct the optimizer.

```
import tensorflow as tf
import tensorflow.keras.backend as K
from keras_gradient_accumulation import AdamAccumulated

optimizer = AdamAccumulated(accumulation_steps=8)
```
returns:

```
  File "C:\Users\user\.conda\envs\TF_EDS\lib\site-packages\keras_gradient_accumulation\optimizer_v1.py", line 39, in __init__
    super(AdamAccumulated, self).__init__(**kwargs) 


TypeError: __init__() missing 1 required positional argument: 'name'
```

I am running a virtual env via conda.

OS: Windows 10
Python: 3.83
Tensor Flow: 2.4.0
Keras: 2.4.3

Sorry if this is a simple error, I am still relatively new to this. Thanks in advance.

**Comment by ghost** [comment]
I'm facing the same issue in Colab.

**Comment by dlamm1997** [comment]
@left-brain  Downgrading to keras 2.3.1 did the trick.

You can do this in Colab with the code below:
```
!pip install keras-gradient-accumulation==0.0.6
!pip uninstall keras
!pip install keras==2.3.1

from keras_gradient_accumulation import AdamAccumulated

opt = AdamAccumulated(accumulation_steps=10)
```
Note you'll have to respond to some prompts for the keras uninstall.


@CyberZHG  Sorry for raising a simple error. Seems the 'bug' is just for keras 2.4.x .

**Comment by CyberZHG** [comment]
Add `TF_KERAS=1` to your environment variables if you want to use `Keras` in `TensorFlow`. The old V1 optimizers were used for the older version of `Keras`.

**Comment by CyberZHG** [comment]
The specification of the optimizers has been changed after 2.4.
